# Generated by Django 3.2 on 2021-04-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40, verbose_name='titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('descropcion', models.CharField(max_length=110, verbose_name='descripcion')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('imagen', models.URLField(max_length=250)),
                ('estado', models.BooleanField(default=True, verbose_name='publico/no publico')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
